// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9OogtMoukGIDy_OeTRbE0qgfqkyC5Uxw',
    appId: '1:637278352622:web:8a5900e020e4040eb16fff',
    messagingSenderId: '637278352622',
    projectId: 'chatapp0backend',
    authDomain: 'chatapp0backend.firebaseapp.com',
    storageBucket: 'chatapp0backend.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZsipMus_VAroYdLdHoeoMXVDOy9evsbc',
    appId: '1:637278352622:android:5b557ebba4abff1eb16fff',
    messagingSenderId: '637278352622',
    projectId: 'chatapp0backend',
    storageBucket: 'chatapp0backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz-089P5uxFLR-C9mkVtCH49U6UwzZC68',
    appId: '1:637278352622:ios:93c537061e029fcfb16fff',
    messagingSenderId: '637278352622',
    projectId: 'chatapp0backend',
    storageBucket: 'chatapp0backend.firebasestorage.app',
    iosBundleId: 'com.example.whatsappUi',
  );
}
